name: Swift

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode 16.1
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1.0'

    - name: Display versions
      run: |
         swift --version
         xcodebuild -version
    
    - name: Display Available Simulators
      run:
        xcrun simctl list devices

    # Run tests using xcodebuild if the package includes UIKit or other iOS frameworks
    - name: Build and Test with xcodebuild
      run: |
        xcodebuild test \
          -scheme Notifly \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=18.1"

